import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

import { Josefin_Sans } from "next/font/google";

const josefinSans = Josefin_Sans({
  weight: ["100", "300", "400", "700"],
  subsets: ["latin"],
  style: ["normal", "italic"],
});

import { IBM_Plex_Sans_Arabic } from "next/font/google";

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  weight: ["400", "700"],
  subsets: ["arabic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${josefinSans.className} ${ibmPlexSansArabic.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
