import localFont from "next/font/local";
import { Roboto } from "@next/font/google";
import "./globals.css";

// Importing Roboto from Google Fonts
const roboto = Roboto({
  weight: ["400", "700"], // Include multiple weights if needed
  subsets: ["latin"],
});

// Josefin Sans font via Google Fonts
import { Josefin_Sans } from "@next/font/google"; // Use the official `@next/font/google` for optimization

const josefinSans = Josefin_Sans({
  weight: ["100", "300", "400", "700"], // Include the variable weights
  subsets: ["latin"],
  style: ["normal", "italic"], // Include styles if necessary
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${josefinSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
